export enum FormFieldType {
  TEXT = 'text',
  EMAIL = 'email',
  PASSWORD = 'password',
  NUMBER = 'number',
  PHONE = 'phone',
  TEXTAREA = 'textarea',
  SELECT = 'select',
  RADIO = 'radio',
  IMAGE = 'image',
  FILE = 'file',
  DATE = 'date',
  TIME = 'time',
  DATETIME = 'datetime',
}
